# Site settings
title: Lifted
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Lifted
description: "An Italian Calisthenics Team"
baseurl: "/lifted"
url: "http://liftedteam.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  lienhard.davide@gmail.com
icon: /img/logo2.png

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
