# Site settings
title: Lifted
header-img: img/home.jpg
email: liftedcalisthenics@gmail.com
copyright_name: Lifted
description: "An Italian Calisthenics Team"
baseurl: ""
telegram_username: hailrend
github_username:  liftedteam
facebook_username:  
email_username:  liftedcalisthenics@gmail.com
icon: /img/logo2.png

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-101080240-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
